class AllowNilsForHqUsers < ActiveRecord::Migration[5.1]
  def change
    change_column_null :hq_users, :first_name, true
    change_column_null :hq_users, :last_name, true
    change_column_null :hq_users, :email, true
    change_column_null :hq_users, :user_type, true
    change_column_null :hq_users, :note, true
    change_column_null :hq_users, :password, true
    change_column_null :hq_users, :address, true
    change_column_null :hq_users, :phone, true
    change_column_null :hq_users, :country, true
    change_column_null :hq_users, :state, true
    change_column_null :hq_users, :city, true
    change_column_null :hq_users, :job_title, true
    change_column_null :hq_users, :company, true
    change_column_null :hq_users, :time_zone, true
    change_column_null :hq_users, :business_name, true
    change_column_null :hq_users, :assigning_tasks, true
    change_column_null :hq_users, :task_notification_emails, true
    change_column_null :hq_users, :fb_audience_confirmation, true
    change_column_null :hq_users, :fb_photo_upload, true
    change_column_null :hq_users, :profile_picture, true
    change_column_null :hq_users, :status, true
    change_column_null :hq_users, :fb_connect, true
    change_column_null :hq_users, :fb_id, true
    change_column_null :hq_users, :access_token, true
    change_column_null :hq_users, :long_live_token, true
    change_column_null :hq_users, :twitter_connect, true
    change_column_null :hq_users, :twitter_id, true
    change_column_null :hq_users, :google_connect, true
    change_column_null :hq_users, :google_id, true
    change_column_null :hq_users, :linkedin_connect, true
    change_column_null :hq_users, :linkedin_id, true
    change_column_null :hq_users, :youtube_connect, true
    change_column_null :hq_users, :youtube_id, true
    change_column_null :hq_users, :date, true
    change_column_null :hq_users, :invite, true
    change_column_null :hq_users, :response, true
    change_column_null :hq_users, :login_time, true
    change_column_null :hq_users, :paid, true
    change_column_null :hq_users, :online, true
    change_column_null :hq_users, :auto_report, true
    change_column_null :hq_users, :report_sent_count, true
    change_column_null :hq_users, :report_sent_date, true
    change_column_null :hq_users, :report_send_date, true
    change_column_null :hq_users, :current_plan, true
    change_column_null :hq_users, :plan_id, true
    change_column_null :hq_users, :plan_amount, true
    change_column_null :hq_users, :expiry_date, true
    change_column_null :hq_users, :expiry_notification_date, true
    change_column_null :hq_users, :purchase_date, true
    change_column_null :hq_users, :last_login, true
    change_column_null :hq_users, :login_location, true
    change_column_null :hq_users, :registered_date, true
    change_column_null :hq_users, :payment_reminder_date, true
    change_column_null :hq_users, :beta, true
    change_column_null :hq_users, :cancel, true
    change_column_null :hq_users, :extended_until, true
    change_column_null :hq_users, :username, true
    change_column_null :hq_users, :Joeycrowd, true
    change_column_null :hq_users, :email_verify, true
    change_column_null :hq_users, :account_limit, true
    change_column_null :hq_users, :encrypted_password, true
    change_column_null :hq_users, :reset_password_token, true
    change_column_null :hq_users, :reset_password_sent_at, true
    change_column_null :hq_users, :remember_created_at, true
    change_column_null :hq_users, :sign_in_count, true
    change_column_null :hq_users, :current_sign_in_at, true
    change_column_null :hq_users, :last_sign_in_at, true
    change_column_null :hq_users, :current_sign_in_ip, true
    change_column_null :hq_users, :last_sign_in_ip, true
    change_column_null :hq_users, :authentication_token, true
    change_column_null :hq_users, :timezone, true
    change_column_null :hq_users, :organisation_id, true
    change_column_null :hq_users, :office_id, true
  end
end
